name: places_search
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_maps_flutter: 2.2.3
  geolocator: 9.0.2
  geocoding: 2.0.5
  http: 0.13.5
  uuid: 3.0.7
  hexcolor: 3.0.1
  google_fonts: 4.0.3
  iconly: 1.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

